# TODO: Quizá es posible configurar cada microservicio por separado
#       e importar cada configuración aquí.
services:
  auth-db:
    container_name: microservice-auth-db
    image: postgres:16.0
    ports:
      - "5431:5432"
    env_file:
      - ./auth/.env.prod

  auth:
    depends_on:
      - auth-db
    container_name: microservice-auth
    build:
      context: ./auth
      dockerfile: Dockerfile

  products:
    depends_on:
      - products-db
    container_name: microservice-products
    build:
      context: ./products
      dockerfile: Dockerfile

  products-db:
    container_name: microservice-products-db
    image: mongodb/mongodb-community-server:6.0.1-ubi8
    ports:
      - "27017:27017"
    env_file:
      - ./products/.env.prod

  gateway:
    container_name: microservice-api-gateway
    image: nginx:1.27.2
    volumes:
      - ./gateway/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
