services:
  db:
    container_name: microservices-auth-db
    image: postgres:17.0
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DATABASE=${DB_NAME}
    ports:
      - "5432:5432"
